--- !<io.dekorate.docker.config.EditableDockerBuildConfig>
project:
  root: file:///home/emmecilab/Documenti/spring-boot-kubernetes-dekorate/
  dekorateInputDir: null
  dekorateOutputDir: META-INF/dekorate
  dekorateMetaDir: ../.dekorate
  buildInfo:
    name: microservice-demo
    version: 0.0.1-SNAPSHOT
    packaging: jar
    buildTool: maven
    buildToolVersion: 3.6.3
    outputFile: file:///home/emmecilab/Documenti/spring-boot-kubernetes-dekorate/target/microservice-demo-0.0.1-SNAPSHOT.jar
    classOutputDir: file:///home/emmecilab/Documenti/spring-boot-kubernetes-dekorate/target/classes/
    resourceDir: file:///home/emmecilab/Documenti/spring-boot-kubernetes-dekorate/src/main/resources/
  scmInfo:
    root: file:///home/emmecilab/Documenti/spring-boot-kubernetes-dekorate/
    branch: main
    commit: 1c00dd29650e69c3c49d166362462f784f6e84bb
    remote:
      '[remote "origin"]': https://github.com/mcicolella/spring-boot-kubernetes-dekorate.git
partOf: null
name: microservice-demo
version: 0.0.1-SNAPSHOT
enabled: true
registry: null
group: emmecilab
image: null
dockerFile: Dockerfile
autoBuildEnabled: false
autoPushEnabled: false
autoLoadEnabled: false
autoDeployEnabled: false
