---
project:
  root: file:///home/emmecilab/Documenti/spring-boot-kubernetes-dekorate/
  dekorateInputDir: null
  dekorateOutputDir: META-INF/dekorate
  dekorateMetaDir: ../.dekorate
  buildInfo:
    name: microservice-demo
    version: 0.0.1-SNAPSHOT
    packaging: jar
    buildTool: maven
    buildToolVersion: 3.6.3
    outputFile: file:///home/emmecilab/Documenti/spring-boot-kubernetes-dekorate/target/microservice-demo-0.0.1-SNAPSHOT.jar
    classOutputDir: file:///home/emmecilab/Documenti/spring-boot-kubernetes-dekorate/target/classes/
    resourceDir: file:///home/emmecilab/Documenti/spring-boot-kubernetes-dekorate/src/main/resources/
  scmInfo:
    root: file:///home/emmecilab/Documenti/spring-boot-kubernetes-dekorate/
    branch: main
    commit: 1c00dd29650e69c3c49d166362462f784f6e84bb
    remote:
      '[remote "origin"]': https://github.com/mcicolella/spring-boot-kubernetes-dekorate.git
partOf: null
name: microservice-demo
version: 0.0.1-SNAPSHOT
deploymentKind: Deployment
workingDir: null
serviceAccount: null
ports:
  - name: http
    containerPort: 8080
    hostPort: 80
    nodePort: null
    path: /
    protocol: null
serviceType: ClusterIP
imagePullPolicy: IfNotPresent
livenessProbe:
  httpActionPath: /actuator/health/liveness
  execAction: null
  tcpSocketAction: null
  grpcAction: null
  initialDelaySeconds: null
  periodSeconds: null
  timeoutSeconds: null
  successThreshold: null
  failureThreshold: null
readinessProbe:
  httpActionPath: /actuator/health/readiness
  execAction: null
  tcpSocketAction: null
  grpcAction: null
  initialDelaySeconds: null
  periodSeconds: null
  timeoutSeconds: null
  successThreshold: null
  failureThreshold: null
startupProbe: null
requestResources: null
limitResources: null
autoDeployEnabled: false
replicas: 1
deploymentStrategy: None
rollingUpdate: null
ingress:
  host: null
  expose: null
  tlsSecretName: null
headless: false
